apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps-app
spec:
  selector:
    app: ftps-app
  ports:
    - port: 21
      nodePort: 21
      protocol: TCP
      name: ftps
    - port: 21000
      nodePort: 21000
      protocol: TCP
      name: ftps-data
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      restartPolicy: Always
      containers:
      - image: my-ftps
        name: my-ftps
        ports:
        - containerPort: 21
          name: my-ftps
        - containerPort: 21000
          name: ftps-data
        imagePullPolicy: Never
        env:
        - name: FTP_USER
          value: rofernan
        - name: FTP_PASS
          value: password
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
