
---

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ftps
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ftps-service
          servicePort: 21
