apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-app
spec:
  selector:
    app: influxdb-app
  ports:
    - port: 8086
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    app: influxdb-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/influxdb
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb.conf
  INFLUXDB_ADMIN_USER: rofernan
  INFLUXDB_ADMIN_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicy: Always
      containers:
      - image: my-influxdb
        name: my-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: my-influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        envFrom:
        - secretRef:
            name: influxdb-secrets
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
