apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-app
spec:
  selector:
    app: influxdb-app
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 8086
      protocol: TCP
      name: http
  type: NodePort
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb-pv-claim
#   labels:
#     app: influxdb-app
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicy: Always
      containers:
      - image: my-influxdb
        name: my-influxdb
        imagePullPolicy: Never
        # env:
        # - name: MYSQL_ROOT_PASSWORD
          # value: password
          # valueFrom:
            # secretKeyRef:
              # name: mysql-pass
              # key: password
        ports:
        - containerPort: 8086
          name: my-influxdb
      #   volumeMounts:
      #   - name: influxdb-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: influxdb-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: influxdb-pv-claim