apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      restartPolicy: Always
      containers:
      - image: my-nginx
        name: my-nginx
        imagePullPolicy: Never
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 443
    protocol: TCP
    name: https
  - port: 22
    targetPort: 22
    nodePort: 22
    protocol: TCP
    name: ssh
  selector:
    app: nginx-app
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
# spec:
#   containers:
#   - name: my-nginx
#     image: my-nginx
#     command: ["sh"]
#     args: ["command.sh"]


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-nginx
#   labels:
#     app: ft_services
# spec:
#   selector:
#     matchLabels:
#       app: ft_services
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: ft_services
#     spec:
#       restartPolicy: Always
#       containers:
#       - name: my-nginx
#         image: my-nginx
#         imagePullPolicy: Never
#         name: my-nginx
#         volumeMounts:
#         - name: nginx-config
#           mountPath: /etc/nginx/nginx.conf
#           subPath: nginx.conf
#           readOnly: true
#         command: [ "/bin/sh", "-ce", "tail -f /dev/null" ]
#       volumes:
#         - name: nginx-config
#           configMap:
#             name: nginx-config
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-nginx
#   labels:
#     app: ft_services
# spec:
#   type: NodePort
#   ports:
#   - port: 32080
#     targetPort: 80
#     protocol: TCP
#     name: http
#   - port: 32443
#     targetPort: 443
#     protocol: TCP
#     name: https
#   - port: 32022
#     nodePort: 32022
#     targetPort: 22
#     protocol: TCP
#     name: ssh
#   selector:
#     app: ft_services